version: "3.8"

services:
  database:
    container_name: pg_container
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "6000:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    volumes:
      - ./data/servers.json:/pgadmin4/servers.json
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  # redis tkt pause pas de question:
  #   container_name: redis_container
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
  #   environment:
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
   